# CODE-ID: docker-compose_dev_v1
#
# Masterplan zum Bauen und Starten der Anwendung auf dem Entwicklungsrechner.
# Diese Datei wird vom `deploy.sh`-Skript verwendet.

version: "3.8"

services:
  # Der API-Dienst (FastAPI)
  api:
    build: . # Baut das Image aus dem Dockerfile im aktuellen Verzeichnis
    command: uvicorn api:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
    volumes:
      # Verbindet den lokalen known_faces-Ordner mit dem im Container.
      - ./known_faces:/app/known_faces
    restart: unless-stopped

  # Der UI-Dienst (Gradio)
  ui:
    build: . # Nutzt dasselbe Image wie die API
    command: python gradio_ui.py
    ports:
      - "7001:7001"
    depends_on:
      - api # Stellt sicher, dass die API vor der UI gestartet wird
    restart: unless-stopped
